services:
    tee_diva:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        image: myapp:latest
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - tee:/app/packages/client-twitter/src/tweetcache
            - tee:/app/db.sqlite
            - ./:/app
        env_file:
            - ./.env
        ports:
            - "3000:3000"
        restart: always
        command: ["pnpm", "start", "--character=characters/gamefidiva.character.json"]

volumes:
    tee:

